// Code generated by protoc-gen-go. DO NOT EDIT.
// source: time.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Serializes a time.Time object as an RFC 3339 encoded string.
type Time struct {
	Rfc3339 []byte `protobuf:"bytes,1,opt,name=rfc3339,proto3" json:"rfc3339,omitempty"`
}

func (m *Time) Reset()                    { *m = Time{} }
func (m *Time) String() string            { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()               {}
func (*Time) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Time) GetRfc3339() []byte {
	if m != nil {
		return m.Rfc3339
	}
	return nil
}

func init() {
	proto.RegisterType((*Time)(nil), "pb.Time")
}

func init() { proto.RegisterFile("time.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 73 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc9, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe0, 0x62, 0x09, 0xc9,
	0xcc, 0x4d, 0x15, 0x92, 0xe0, 0x62, 0x2f, 0x4a, 0x4b, 0x36, 0x36, 0x36, 0xb6, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x93, 0xd8, 0xc0, 0x8a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x47, 0x0e, 0x2f, 0x6d, 0x3a, 0x00, 0x00, 0x00,
}
